'use strict';

const debug = require('debug')('api:models:producto');
const _ = require('lodash');

/* eslint-disable max-len */
const CODIGO_UNICO_PRODUCTO = [
  {code: '01', name: 'ANIMALES VIVOS'},
  {code: '02', name: 'CARNE Y DESPOJOS COMESTIBLES'},
  {code: '03', name: 'PESCADOS Y CRUSTACEOS, MOLUSCOS Y DEMAS INVERTEBRADOS ACUATICOS'},
  {code: '04', name: 'LECHE Y PRODUCTOS LACTEOS; HUEVOS DE AVE; MIEL NATURAL; PRODUCTOS COMESTIBLES DE ORIGEN ANIMAL, NO EXPRESADOS NI COMPRENDIDOS EN OTRA PARTE.'},
  {code: '05', name: 'LOS DEMAS PRODUCTOS DE ORIGEN ANIMAL NO EXPRESADOS NI COMPRENDIDOS EN OTRA PARTE'},
  {code: '06', name: 'PLANTAS VIVAS Y PRODUCTOS DE LA FLORICULTURA'},
  {code: '07', name: 'HORTALIZAS (INCLUSO SILVESTRES), PLANTAS, RAICES Y TUBERCULOS ALIMENTICIOS'},
  {code: '08', name: 'FRUTAS Y FRUTOS COMESTIBLES; CORTEZAS DE AGRIOS (CITRICOS), MELONES O SANDIAS'},
  {code: '09', name: 'CAFE, TE, YERBA MATE Y ESPECIAS'},
  {code: '10', name: 'CEREALES'},
  {code: '11', name: 'PRODUCTOS DE LA MOLINERIA; MALTA; ALMIDON Y FECULA; INULINA; GLUTEN DE TRIGO'},
  {code: '12', name: 'SEMILLAS Y FRUTOS OLEAGINOSOS; SEMILLAS Y FRUTOS DIVERSOS; PLANTAS INDUSTRIALES O MEDICINALES; PAJA Y FORRAJE'},
  {code: '13', name: 'GOMAS, RESINAS Y DEMAS JUGOS Y EXTRACTOS VEGETALES'},
  {code: '14', name: 'MATERIAS TRENZABLES Y DEMAS PRODUCTOS DE ORIGEN VEGETAL, NO EXPRESADOS NI COMPRENDIDOS EN OTRA PARTE'},
  {code: '15', name: 'GRASAS Y ACEITES ANIMALES O VEGETALES; PRODUCTOS DE SU DESDOBLAMIENTO; GRASAS ALIMENTICIAS ELABORADAS; CERAS DE ORIGEN ANIMAL O VEGETAL'},
  {code: '16', name: 'PREPARACIONES DE CARNE, PESCADO O DE CRUSTACEOS, MOLUSCOS O DEMAS INVERTEBRADOS ACUATICOS'},
  {code: '17', name: 'AZUCARES Y ARTICULOS DE CONFITERIA'},
  {code: '18', name: 'CACAO Y SUS PREPARACIONES'},
  {code: '19', name: 'PREPARACIONES A BASE DE CEREALES, HARINA, ALMIDON, FECULA O LECHE; PRODUCTOS DE PASTELERIA'},
  {code: '20', name: 'PREPARACIONES DE HORTALIZAS (INCLUSO SILVESTRES), FRUTAS U OTROS FRUTOS O DEMAS PARTES DE PLANTAS'},
  {code: '21', name: 'PREPARACIONES ALIMENTICIAS DIVERSAS'},
  {code: '22', name: 'BEBIDAS, LIQUIDOS ALCOHOLICOS Y VINAGRE'},
  {code: '23', name: 'RESIDUOS Y DESPERDICIOS DE LAS INDUSTRIAS ALIMENTARIAS; ALIMENTOS PREPARADOS PARA ANIMALES'},
  {code: '24', name: 'TABACO Y SUCEDANEOS DEL TABACO ELABORADOS'},
  {code: '25', name: 'SAL; AZUFRE; TIERRAS Y PIEDRAS; YESOS, CALES Y CEMENTOS'},
  {code: '26', name: 'MINERALES METALIFEROS, ESCORIAS Y CENIZAS'},
  {code: '27', name: 'COMBUSTIBLES MINERALES, ACEITES MINERALES Y PRODUCTOS DE SU DESTILACION; MATERIAS BITUMINOSAS; CERAS MINERALES'},
  {code: '28', name: 'PRODUCTOS QUIMICOS INORGANICOS; COMPUESTOS INORGANICOS U ORGANICOS DE METAL PRECIOSO, DE ELEMENTOS RADIACTIVOS, DE METALES DE LAS TIERRAS RARAS O DE ISOTOPOS'},
  {code: '29', name: 'PRODUCTOS QUIMICOS ORGANICOS'},
  {code: '30', name: 'PRODUCTOS FARMACEUTICOS'},
  {code: '31', name: 'ABONOS'},
  {code: '32', name: 'EXTRACTOS CURTIENTES O TINTOREOS; TANINOS Y SUS DERIVADOS; PIGMENTOS Y DEMAS MATERIAS COLORANTES; PINTURAS Y BARNICES; MASTIQUES; TINTAS'},
  {code: '33', name: 'ACEITES ESENCIALES Y RESINOIDES; PREPARACIONES DE PERFUMERIA, TOCADOR O COSMETICA'},
  {code: '34', name: 'JABON, AGENTES DE SUPERFICIE ORGANICOS, PREPARACIONES PARA LAVAR, PREPARACIONES LUBRICANTES, CERAS ARTIFICIALES, CERAS PREPARADAS, PRODUCTOS DE LIMPIEZA, VELAS Y ARTICULOS SIMILARES, PASTAS PARA MODELAR, CERAS PARA ODONTOLOGIA Y PREPARACIONES PARA ODONTOLOGIA A BASE DE YESO FRAGUABLE'},
  {code: '35', name: 'MATERIAS ALBUMINOIDEAS; PRODUCTOS A BASE DE ALMIDON O FECULA MODIFICADOS; COLAS; ENZIMAS'},
  {code: '36', name: 'POLVORA Y EXPLOSIVOS; ARTICULOS DE PIROTECNIA; FOSFOROS (CERILLAS); ALEACIONES PIROFORICAS; MATERIAS INFLAMABLES'},
  {code: '37', name: 'PRODUCTOS FOTOGRAFICOS O CINEMATOGRAFICOS'},
  {code: '38', name: 'PRODUCTOS DIVERSOS DE LAS INDUSTRIAS QUIMICAS'},
  {code: '39', name: 'PLASTICO Y SUS MANUFACTURAS'},
  {code: '40', name: 'CAUCHO Y SUS MANUFACTURAS'},
  {code: '41', name: 'PIELES (EXCEPTO LA PELETERIA) Y CUEROS'},
  {code: '42', name: 'MANUFACTURAS DE CUERO; ARTICULOS DE TALABARTERIA O GUARNICIONERIA; ARTICULOS DE VIAJE, BOLSOS DE MANO (CARTERAS) Y CONTINENTES SIMILARES; MANUFACTURAS DE TRIPA'},
  {code: '43', name: 'PELETERIA Y CONFECCIONES DE PELETERIA; PELETERIA FACTICA O ARTIFICIAL'},
  {code: '44', name: 'MADERA, CARBON VEGETAL Y MANUFACTURAS DE MADERA; CORCHO Y SUS MANUFACTURAS; MANUFACTURAS DE ESPARTERIA O CESTERIA'},
  {code: '45', name: 'CORCHO Y SUS MANUFACTURAS'},
  {code: '46', name: 'MANUFACTURAS DE ESPARTERIA O CESTERIA'},
  {code: '47', name: 'PASTA DE MADERA O DE LAS DEMAS MATERIAS FIBROSAS CELULOSICAS; PAPEL O CARTON PARA RECICLAR (DESPERDICIOS Y DESECHOS)'},
  {code: '48', name: 'PAPEL Y CARTON; MANUFACTURAS DE PASTA DE CELULOSA, DE PAPEL O CARTON'},
  {code: '49', name: 'PRODUCTOS EDITORIALES DE LA PRENSA Y DE LAS DEMAS INDUSTRIAS GRAFICAS; TEXTOS MANUSCRITOS O MECANOGRAFIADOS Y PLANOS'},
  {code: '50', name: 'SEDA'},
  {code: '51', name: 'LANA Y PELO FINO U ORDINARIO; HILADOS Y TEJIDOS DE CRIN'},
  {code: '52', name: 'ALGODON'},
  {code: '53', name: 'LAS DEMAS FIBRAS TEXTILES VEGETALES; HILADOS DE PAPEL Y TEJIDOS DE HILADOS DE PAPEL'},
  {code: '54', name: 'FILAMENTOS SINTETICOS O ARTIFICIALES'},
  {code: '55', name: 'FIBRAS SINTETICAS O ARTIFICIALES DISCONTINUAS'},
  {code: '56', name: 'GUATA, FIELTRO Y TELA SIN TEJER; HILADOS ESPECIALES; CORDELES, CUERDAS Y CORDAJES; ARTICULOS DE CORDELERIA'},
  {code: '57', name: 'ALFOMBRAS Y DEMAS REVESTIMIENTOS PARA EL SUELO, DE MATERIA TEXTIL'},
  {code: '58', name: 'TEJIDOS ESPECIALES; SUPERFICIES TEXTILES CON MECHON INSERTADO; ENCAJES; TAPICERIA; PASAMANERIA; BORDADOS'},
  {code: '59', name: 'TELAS IMPREGNADAS, RECUBIERTAS, REVESTIDAS O ESTRATIFICADAS; ARTICULOS TECNICOS DE MATERIA TEXTIL'},
  {code: '60', name: 'TEJIDOS DE PUNTO'},
  {code: '61', name: 'PRENDAS Y COMPLEMENTOS (ACCESORIOS), DE VESTIR, DE PUNTO'},
  {code: '62', name: 'PRENDAS Y COMPLEMENTOS (ACCESORIOS) DE VESTIR, EXCEPTO LOS DE PUNTO'},
  {code: '63', name: 'LOS DEMAS ARTICULOS TEXTILES CONFECCIONADOS; JUEGOS; PRENDERIA Y TRAPOS'},
  {code: '64', name: 'CALZADO, SOMBREROS Y DEMAS TOCADOS, PARAGUAS, QUITASOLES, BASTONES, LATIGOS, FUSTAS, Y SUS PARTES; PLUMAS PREPARADAS Y ARTICULOS DE PLUMAS; FLORES ARTIFICIALES; MANUFACTURAS DE CABELLO'},
  {code: '65', name: 'SOMBREROS, DEMAS TOCADOS, Y SUS PARTES'},
  {code: '66', name: 'PARAGUAS, SOMBRILLAS, QUITASOLES, BASTONES, BASTONES ASIENTO, LATIGOS, FUSTAS, Y SUS PARTES'},
  {code: '67', name: 'PLUMAS Y PLUMON PREPARADOS Y ARTICULOS DE PLUMAS O PLUMON; FLORES ARTIFICIALES; MANUFACTURAS DE CABELLO'},
  {code: '68', name: 'MANUFACTURAS DE PIEDRA, YESO FRAGUABLE, CEMENTO, AMIANTO (ASBESTO), MICA O MATERIAS ANALOGAS.'},
  {code: '69', name: 'PRODUCTOS CERAMICOS'},
  {code: '70', name: 'VIDRIO Y SUS MANUFACTURAS'},
  {code: '71', name: 'PERLAS NATURALES (FINAS) O CULTIVADAS, PIEDRAS PRECIOSAS O SEMIPRECIOSAS, METALES PRECIOSOS, CHAPADOS DE METAL PRECIOSO (PLAQUE) Y MANUFACTURAS DE ESTAS MATERIAS; BISUTERIA; MONEDAS'},
  {code: '72', name: 'FUNDICCION, HIERRO Y ACERO'},
  {code: '73', name: 'MANUFACTURAS DE FUNDICION, HIERRO O ACERO'},
  {code: '74', name: 'COBRE Y SIS MANUFACTURAS'},
  {code: '75', name: 'NIQUEL Y SUS MANUFACTURAS'},
  {code: '76', name: 'ALUMINIO Y SUS MANUFACTURAS'},
  {code: '78', name: 'PLOMO Y SUS MANUFACTURAS'},
  {code: '79', name: 'CINC Y SUS MANUFACTURAS'},
  {code: '80', name: 'ESTAÑO Y SUS MANUFACTURAS'},
  {code: '81', name: 'LOS DEMAS METALES COMUNES; CERMETS; MANUFACTURAS DE ESTAS MATERIAS'},
  {code: '82', name: 'HERRAMIENTAS Y UTILES, ARTICULOS DE CUCHILLERIA Y CUBIERTOS DE MESA, DE METAL COMUN; PARTES DE ESTOS ARTICULOS DE METAL COMUN'},
  {code: '83', name: 'MANUFACTURAS DIVERSAS DE METAL COMUN'},
  {code: '84', name: 'REACTORES NUCLEARES, CALDERAS, MAQUINAS, APARATOS Y ARTEFACTOS MECANICOS; PARTES DE ESTAS MAQUINAS O APARATOS'},
  {code: '85', name: 'MAQUINAS, APARATOS Y MATERIAL ELECTRICO, Y SUS PARTES; APARATOS DE GRABACION O REPRODUCCION DE SONIDO, APARATOS DE GRABACION Y REPRODUCCION DE IMAGEN Y SONIDO EN TELEVISION, Y LAS PARTES Y ACCESORIOS DE ESTOS APARATOS'},
  {code: '86', name: 'VEHICULOS Y MATERIAL PARA VIAS FERREAS O SIMILARES, Y SUS PARTES; APARATOS MECANICOS (INCLUSO ELECTROMECANICOS) DE SEÑALIZACION PARA VIAS DE COMUNICACION'},
  {code: '87', name: 'VEHICULOS, AUTOMOVILES, TRACTORES, VELOCOPEDOS Y DEMAS VEHICULOS TERRESTRES; SUS PARTES Y ACCESORIOS'},
  {code: '88', name: 'AERONAVES, VEHICULOS ESPACIALES Y SUS PARTES'},
  {code: '89', name: 'BARCOS Y DEMAS ESTRUCTURAS FLOTANTES'},
  {code: '90', name: 'INSTRUMENTOS Y APARATOS DE OPTICA, FOTOGRAFIA Y CINEMATROGRAFIA, DE MEDIDA, CONTROL O PRECISION; INSTRUMENTOS Y APARATOS MEDICOQUIRURGICOS; PARTES Y ACCESORIOS DE ESTOS INSTRUMENTOS O APARATOS'},
  {code: '91', name: 'APARATOS DE RELOJERIA Y SUS PARTES'},
  {code: '92', name: 'INSTRUMENTOS MUSICALES; SUS PARTES Y ACCESORIOS'},
  {code: '93', name: 'ARMAS Y MUNICIONES; SUS PARTES Y ACCESORIOS'},
  {code: '94', name: 'MUEBLES; MOBILIARIO MEDICOQUIRURGICO; ARTICULOS DE CAMA Y SIMILARES; APARATOS DE ALUMBRADO NO EXPRESADOS NI COMPRENDIDOS EN OTRA PARTE; ANUNCIOS, LETREROS Y PLACAS INDICADORAS LUMINOSOS, Y ARTICULOS SIMILARES; CONSTRUCCIONES PREFABRICADAS'},
  {code: '95', name: 'JUGUETES, JUEGOS Y ARTICULOS PARA RECREO O DEPORTE; SUS PARTES Y ACCESORIOS'},
  {code: '96', name: 'MANUFACTURAS DIVERSAS'},
  {code: '97', name: 'OBJETOS DE ARTE O COLECCION Y ANTIGUEDADES'},
];
/* eslint-enable max-len */

const UNIDADES_MEDIDA = [
  {code: '1',	name: 'Kilogramos'},
  {code: '2',	name: 'Litros'},
  {code: '3',	name: 'Unidades'},
  {code: '4',	name: 'Metros cuadrados'},
  {code: '5',	name: 'Metros'},
  {code: '6',	name: 'Metros Cúbicos'},
  {code: '7',	name: 'Pares'},
];

module.exports = function(Producto) {
  // codigo_unico_producto validation
  // Producto.validate('codigo_unico_producto', function(error) {
  //   const producto = this;
  //   const isValid = _.find(CODIGO_UNICO_PRODUCTO, (cot) => {
  //     return producto.codigo_unico_producto == cot.code;
  //   });
  //   if (!isValid) error();
  // }, {
  //   message: 'parametro invalido: codigo_unico_producto',
  // });

  // rentas_codigo_unidad_medida validation
  Producto.validate('rentas_codigo_unidad_medida', function(error) {
    const producto = this;
    const isValid = _.find(UNIDADES_MEDIDA, (u) => {
      return producto.rentas_codigo_unidad_medida == u.code;
    });
    if (!isValid) error();
  }, {
    message: 'parametro invalido: rentas_codigo_unidad_medida',
  });
};
